name: Azure CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
      - name: 'Check if infrastructure code has changed'
        id: infrastructure-code
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: |
            azuredeploy.bicep
            azuredeploy.parameters.json
      - name: 'Deploy infrastructure'
        if: steps.infrastructure-code.outputs.diff
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azuredeploy.bicep
          parameters: ./azuredeploy.parameters.json
          failOnStdErr: false
          deploymentMode: Complete
